import { useState, useEffect } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import {
  Map, Sparkles, CheckCircle, Circle, ArrowRight, Loader, Download,
  Trash2, ChevronDown, ChevronUp, BookOpen, Clock, Target, BarChart2
} from 'lucide-react';
import Button from '../components/Button';
import './Roadmaps.css';

const API_URL = '/api';
const STORAGE_KEY = 'skillxchange_roadmaps';

function loadSaved() {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');
  } catch {
    return [];
  }
}

function saveToStorage(roadmaps) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(roadmaps));
}

export default function Roadmaps() {
  const { user } = useAuth();
  const [skillInput, setSkillInput] = useState('');
  const [levelInput, setLevelInput] = useState('Beginner');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [roadmap, setRoadmap] = useState(null);
  const [savedRoadmaps, setSavedRoadmaps] = useState(loadSaved);
  const [expandedWeek, setExpandedWeek] = useState(null);
  const [activeView, setActiveView] = useState('generate'); // 'generate' | 'saved'

  // Persist saved roadmaps on change
  useEffect(() => {
    saveToStorage(savedRoadmaps);
  }, [savedRoadmaps]);

  // Auto-expand first week when roadmap loads
  useEffect(() => {
    if (roadmap) setExpandedWeek(0);
  }, [roadmap]);

  const generateRoadmap = async (e) => {
    e.preventDefault();
    if (!skillInput.trim()) return;
    setError('');
    setLoading(true);
    try {
      const res = await axios.post(`${API_URL}/ai/roadmap`, {
        skill: skillInput.trim(),
        level: levelInput
      });
      setRoadmap({ ...res.data, _saved: false });
    } catch (err) {
      console.error(err);
      setError(`Failed to generate roadmap. Error: ${err.response?.status || err.message}`);
    } finally {
      setLoading(false);
    }
  };

  const toggleTask = (weekIndex, taskId) => {
    if (!roadmap) return;
    const newWeeks = roadmap.weeks.map((week, wi) => {
      if (wi !== weekIndex) return week;
      return {
        ...week,
        tasks: week.tasks.map(t => t.id === taskId ? { ...t, done: !t.done } : t)
      };
    });
    const updated = { ...roadmap, weeks: newWeeks };
    setRoadmap(updated);
    // If it's already saved, update in storage too
    if (roadmap._saved) {
      setSavedRoadmaps(prev => prev.map(r => r.id === roadmap.id ? updated : r));
    }
  };

  const saveRoadmap = () => {
    if (!roadmap || roadmap._saved) return;
    const toSave = { ...roadmap, _saved: true };
    setSavedRoadmaps(prev => [toSave, ...prev]);
    setRoadmap(toSave);
  };

  const deleteSaved = (id) => {
    setSavedRoadmaps(prev => prev.filter(r => r.id !== id));
    if (roadmap?.id === id) setRoadmap(null);
  };

  const loadRoadmap = (r) => {
    setRoadmap(r);
    setActiveView('generate');
    setExpandedWeek(0);
  };

  const downloadRoadmap = (r) => {
    const target = r || roadmap;
    if (!target) return;

    const totalDone = target.weeks.reduce((s, w) => s + w.tasks.filter(t => t.done).length, 0);
    const totalTasks = target.weeks.reduce((s, w) => s + w.tasks.length, 0);
    const progress = Math.round((totalDone / totalTasks) * 100);

    let text = `====================================================\n`;
    text += `  SKILLXCHANGE — AI LEARNING ROADMAP\n`;
    text += `====================================================\n\n`;
    text += `Skill:      ${target.skill} (${target.level})\n`;
    text += `Duration:   ${target.estimatedCompletion}\n`;
    text += `Progress:   ${totalDone}/${totalTasks} tasks (${progress}%)\n`;
    text += `Generated:  ${new Date(target.createdAt).toLocaleDateString()}\n\n`;

    target.weeks.forEach(week => {
      text += `────────────────────────────────────\n`;
      text += `Week ${week.week}: ${week.title}\n`;
      text += `────────────────────────────────────\n`;
      week.tasks.forEach(task => {
        const mark = task.done ? '✓' : '○';
        text += `  ${mark}  ${task.text}\n`;
      });
      text += '\n';
    });

    text += `====================================================\n`;
    text += `  Generated by SkillXchange Platform\n`;
    text += `====================================================\n`;

    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${target.skill.replace(/\s+/g, '-')}-${target.level}-Roadmap.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getProgress = (r) => {
    const done = r.weeks.reduce((s, w) => s + w.tasks.filter(t => t.done).length, 0);
    const total = r.weeks.reduce((s, w) => s + w.tasks.length, 0);
    return total > 0 ? Math.round((done / total) * 100) : 0;
  };

  const currentProgress = roadmap ? getProgress(roadmap) : 0;

  return (
    <div className="roadmaps-page container fade-in">
      {/* Header */}
      <div className="roadmaps-header">
        <div className="roadmaps-header-text">
          <h1><Map className="header-icon" /> AI Learning Roadmaps</h1>
          <p className="text-muted">Generate a personalized, step-by-step learning path for any skill.</p>
        </div>
        {savedRoadmaps.length > 0 && (
          <div className="roadmap-view-toggle">
            <button
              className={`view-tab ${activeView === 'generate' ? 'active' : ''}`}
              onClick={() => setActiveView('generate')}
            >
              <Sparkles size={15} /> Generate
            </button>
            <button
              className={`view-tab ${activeView === 'saved' ? 'active' : ''}`}
              onClick={() => setActiveView('saved')}
            >
              <BookOpen size={15} /> Saved ({savedRoadmaps.length})
            </button>
          </div>
        )}
      </div>

      {/* ===== SAVED ROADMAPS VIEW ===== */}
      {activeView === 'saved' && (
        <div className="saved-roadmaps-grid fade-in">
          {savedRoadmaps.map(r => {
            const prog = getProgress(r);
            return (
              <div key={r.id} className="saved-roadmap-card glass-panel">
                <div className="saved-card-header">
                  <div>
                    <h3>{r.skill}</h3>
                    <span className="level-pill">{r.level}</span>
                  </div>
                  <div className="saved-card-actions">
                    <button className="icon-btn" onClick={() => downloadRoadmap(r)} title="Download">
                      <Download size={16} />
                    </button>
                    <button className="icon-btn danger" onClick={() => deleteSaved(r.id)} title="Delete">
                      <Trash2 size={16} />
                    </button>
                  </div>
                </div>
                <div className="progress-bar-wrapper">
                  <div className="progress-bar-fill" style={{ width: `${prog}%` }} />
                </div>
                <div className="saved-card-meta">
                  <span><Clock size={12} /> {r.estimatedCompletion}</span>
                  <span><Target size={12} /> {prog}% complete</span>
                </div>
                <Button variant="ghost" className="w-full mt-3" onClick={() => loadRoadmap(r)}>
                  Continue Learning →
                </Button>
              </div>
            );
          })}
        </div>
      )}

      {/* ===== GENERATE VIEW ===== */}
      {activeView === 'generate' && (
        <>
          {!roadmap && !loading && (
            <div className="generate-card glass-panel glow-border">
              <div className="card-icon">
                <Sparkles size={32} />
              </div>
              <h2>What do you want to learn?</h2>
              <p className="text-muted text-sm mt-1 mb-4">
                Enter any skill — React, Python, UI Design, Machine Learning — and get a personalized roadmap.
              </p>
              <form onSubmit={generateRoadmap} className="generate-form">
                <div className="form-row">
                  <input
                    type="text"
                    placeholder="e.g. React, Python, UI/UX, Machine Learning"
                    value={skillInput}
                    onChange={(e) => setSkillInput(e.target.value)}
                    className="modal-input-field"
                    required
                  />
                  <select
                    value={levelInput}
                    onChange={(e) => setLevelInput(e.target.value)}
                    className="modal-input-field select-field"
                  >
                    <option value="Beginner">Beginner</option>
                    <option value="Intermediate">Intermediate</option>
                    <option value="Advanced">Advanced</option>
                  </select>
                </div>
                {error && <p className="text-error text-sm mt-2">{error}</p>}
                <Button type="submit" className="w-full mt-4 generate-btn">
                  <Sparkles size={16} /> Generate AI Roadmap <ArrowRight size={16} />
                </Button>
              </form>

              {/* Quick skill suggestions */}
              <div className="skill-suggestions mt-4">
                {['React', 'Python', 'UI/UX', 'Machine Learning', 'JavaScript', 'Figma'].map(s => (
                  <button
                    key={s}
                    className="suggestion-chip"
                    type="button"
                    onClick={() => setSkillInput(s)}
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>
          )}

          {loading && (
            <div className="loading-state">
              <div className="loading-animation">
                <Loader className="spinner" size={40} />
              </div>
              <h3>Crafting your personalized roadmap...</h3>
              <p className="text-muted text-sm">
                Analyzing <strong>{skillInput}</strong> curriculum for {levelInput} level learners.
              </p>
            </div>
          )}

          {roadmap && !loading && (
            <div className="roadmap-view fade-in">
              {/* Roadmap Header */}
              <div className="roadmap-hero glass-panel">
                <div className="roadmap-hero-content">
                  <div>
                    <span className="roadmap-skill-eyebrow">AI Roadmap</span>
                    <h2>{roadmap.skill}</h2>
                    <div className="roadmap-meta-pills">
                      <span className="meta-pill"><BarChart2 size={12} /> {roadmap.level}</span>
                      <span className="meta-pill"><Clock size={12} /> {roadmap.estimatedCompletion}</span>
                      <span className="meta-pill"><Target size={12} /> {roadmap.totalTasks} tasks</span>
                      {roadmap.aiGenerated && (
                        <span className="meta-pill ai-pill"><Sparkles size={12} /> AI Generated</span>
                      )}
                    </div>
                  </div>
                  <div className="roadmap-progress-circle">
                    <svg viewBox="0 0 64 64" className="progress-ring">
                      <circle cx="32" cy="32" r="28" fill="none" stroke="var(--border-glass)" strokeWidth="5" />
                      <circle
                        cx="32" cy="32" r="28" fill="none"
                        stroke="var(--brand-primary)" strokeWidth="5"
                        strokeDasharray={`${2 * Math.PI * 28}`}
                        strokeDashoffset={`${2 * Math.PI * 28 * (1 - currentProgress / 100)}`}
                        strokeLinecap="round"
                        transform="rotate(-90 32 32)"
                        style={{ transition: 'stroke-dashoffset 0.5s ease' }}
                      />
                    </svg>
                    <span className="progress-text">{currentProgress}%</span>
                  </div>
                </div>

                <div className="roadmap-actions-bar">
                  <Button variant="ghost" onClick={() => { setRoadmap(null); setSkillInput(''); }}>
                    ← New Roadmap
                  </Button>
                  {!roadmap._saved ? (
                    <Button className="btn-primary" onClick={saveRoadmap}>
                      <BookOpen size={16} /> Save Roadmap
                    </Button>
                  ) : (
                    <span className="saved-badge">✓ Saved</span>
                  )}
                  <Button variant="ghost" onClick={() => downloadRoadmap(null)}>
                    <Download size={16} /> Download
                  </Button>
                </div>
              </div>

              {/* Week-by-week Timeline */}
              <div className="roadmap-timeline mt-4">
                {roadmap.weeks.map((week, wIndex) => {
                  const weekDone = week.tasks.filter(t => t.done).length;
                  const weekTotal = week.tasks.length;
                  const weekPct = Math.round((weekDone / weekTotal) * 100);
                  const isOpen = expandedWeek === wIndex;

                  return (
                    <div key={wIndex} className={`roadmap-week glass-panel ${isOpen ? 'open' : ''}`}>
                      <div
                        className="week-header"
                        onClick={() => setExpandedWeek(isOpen ? null : wIndex)}
                      >
                        <div className="week-number">
                          <span>W{week.week}</span>
                        </div>
                        <div className="week-info">
                          <h4>{week.title}</h4>
                          <div className="week-mini-progress">
                            <div className="week-progress-bar">
                              <div className="week-progress-fill" style={{ width: `${weekPct}%` }} />
                            </div>
                            <span className="text-muted" style={{ fontSize: '0.75rem', whiteSpace: 'nowrap' }}>
                              {weekDone}/{weekTotal}
                            </span>
                          </div>
                        </div>
                        <button className="week-toggle-btn">
                          {isOpen ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                        </button>
                      </div>

                      {isOpen && (
                        <div className="week-tasks fade-in">
                          {week.tasks.map(task => (
                            <div
                              key={task.id}
                              className={`roadmap-task ${task.done ? 'task-done' : ''}`}
                              onClick={() => toggleTask(wIndex, task.id)}
                            >
                              {task.done
                                ? <CheckCircle size={20} className="check-icon" />
                                : <Circle size={20} className="circle-icon" />
                              }
                              <span className="task-text">{task.text}</span>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
